version: "3.7"
services:

    app:
        build: ./
        container_name: citizen_app
        ports:
            - "4000:4000"
        volumes:
            - ./:/app
            - /app/node_modules
        env_file:
            - ./src/.env
        restart: "on-failure"
        command: ["npm", "run", "dev"]
        
volumes:
    data:
